"""create users table

Revision ID: 46bf5f63e42f
Revises: 
Create Date: 2026-03-04 12:38:32.269070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '46bf5f63e42f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('super_admin', 'case_manager', 'advocate', 'staff', name='user_role'), nullable=False),
    sa.Column('designation', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('active', 'locked', 'disabled', name='user_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('case_imports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('uploaded', 'validated', 'imported', 'failed', name='import_status'), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('success_rows', sa.Integer(), nullable=False),
    sa.Column('failed_rows', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_code', sa.String(), nullable=False),
    sa.Column('ref_no', sa.String(), nullable=True),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('agreement_no', sa.String(), nullable=True),
    sa.Column('agreement_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('assigned_advocate_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('allocated_at', sa.Date(), nullable=True),
    sa.Column('zone', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('branch_code', sa.String(), nullable=True),
    sa.Column('branch_name', sa.String(), nullable=True),
    sa.Column('product', sa.String(), nullable=True),
    sa.Column('repossession_status', sa.String(), nullable=True),
    sa.Column('dpd', sa.String(), nullable=True),
    sa.Column('allocation_pos', sa.String(), nullable=True),
    sa.Column('claim_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('claim_date', sa.Date(), nullable=True),
    sa.Column('amount_financed', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('finance_charge', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('agreement_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('award_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('award_amount_words', sa.String(), nullable=True),
    sa.Column('make', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('engine_no', sa.String(), nullable=True),
    sa.Column('chassis_no', sa.String(), nullable=True),
    sa.Column('reg_no', sa.String(), nullable=True),
    sa.Column('first_emi_date', sa.Date(), nullable=True),
    sa.Column('last_emi_date', sa.Date(), nullable=True),
    sa.Column('tenure', sa.Integer(), nullable=True),
    sa.Column('sec_17_applied', sa.String(), nullable=True),
    sa.Column('sec_17_applied_date', sa.Date(), nullable=True),
    sa.Column('sec_17_received_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_advocate_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agreement_no'),
    sa.UniqueConstraint('case_code')
    )
    op.create_index(op.f('ix_cases_assigned_advocate_id'), 'cases', ['assigned_advocate_id'], unique=False)
    op.create_index(op.f('ix_cases_ref_no'), 'cases', ['ref_no'], unique=False)
    op.create_index(op.f('ix_cases_status'), 'cases', ['status'], unique=False)
    op.create_table('case_arbitration',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('institution_name', sa.String(), nullable=True),
    sa.Column('arbitrator_name', sa.String(), nullable=True),
    sa.Column('arbitrator_phone', sa.String(), nullable=True),
    sa.Column('arbitrator_email', sa.String(), nullable=True),
    sa.Column('arbitrator_address', sa.String(), nullable=True),
    sa.Column('acceptance_date', sa.Date(), nullable=True),
    sa.Column('arb_case_no', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_table('case_import_rows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('import_id', sa.UUID(), nullable=False),
    sa.Column('row_no', sa.Integer(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('success', 'failed', name='import_row_status'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['import_id'], ['case_imports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_import_rows_import_id'), 'case_import_rows', ['import_id'], unique=False)
    op.create_table('case_milestones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('milestone_type', sa.Enum('FIRST_MEETING', 'SECOND_MEETING', 'THIRD_MEETING_EXPARTE', 'EVIDENCE_ARGUMENT', 'AWARD_DATE', 'STAMP_PURCHASE_DATE', name='milestone_type'), nullable=False),
    sa.Column('planned_date', sa.Date(), nullable=True),
    sa.Column('actual_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_milestones_case_id'), 'case_milestones', ['case_id'], unique=False)
    op.create_table('case_parties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('party_type', sa.Enum('applicant', 'co_applicant', 'guarantor', name='party_type'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('father_name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_parties_case_id'), 'case_parties', ['case_id'], unique=False)
    op.create_table('case_rules_state',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('notice_count', sa.Integer(), nullable=False),
    sa.Column('closure_enabled', sa.Boolean(), nullable=False),
    sa.Column('closure_enabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_table('meetings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('meet_provider', sa.Enum('google_meet', name='meet_provider'), nullable=False),
    sa.Column('meet_url', sa.String(), nullable=True),
    sa.Column('portal_url', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'completed', 'cancelled', name='meeting_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meetings_case_id'), 'meetings', ['case_id'], unique=False)
    op.create_index(op.f('ix_meetings_scheduled_at'), 'meetings', ['scheduled_at'], unique=False)
    op.create_table('notices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('notice_no', sa.Integer(), nullable=False),
    sa.Column('notice_type', sa.String(), nullable=True),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'sent', 'failed', name='notice_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notices_case_id'), 'notices', ['case_id'], unique=False)
    op.create_table('otp_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('victim_contact', sa.String(), nullable=False),
    sa.Column('otp_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('session_token', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_token')
    )
    op.create_index(op.f('ix_otp_sessions_case_id'), 'otp_sessions', ['case_id'], unique=False)
    op.create_index(op.f('ix_otp_sessions_expires_at'), 'otp_sessions', ['expires_at'], unique=False)
    op.create_table('victim_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_victim_accounts_case_id'), 'victim_accounts', ['case_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_type', sa.Enum('internal', 'victim', 'system', name='actor_type'), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('actor_victim_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['actor_victim_id'], ['victim_accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.UUID(), nullable=True),
    sa.Column('uploaded_by_victim_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.Enum('internal', 'victim', name='doc_source'), nullable=False),
    sa.Column('category', sa.Enum('ID_PROOF', 'LOAN_DOC', 'NOTICE', 'OTHER', name='doc_category'), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('checksum_sha256', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by_victim_id'], ['victim_accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_case_id'), 'documents', ['case_id'], unique=False)
    op.create_table('notice_deliveries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('notice_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Enum('sms', 'whatsapp', 'email', name='delivery_channel'), nullable=False),
    sa.Column('to_address', sa.String(), nullable=False),
    sa.Column('provider_message_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('queued', 'sent', 'delivered', 'read', 'failed', name='delivery_status'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['notice_id'], ['notices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notice_deliveries_notice_id'), 'notice_deliveries', ['notice_id'], unique=False)
    op.create_table('recordings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=True),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('checksum_sha256', sa.String(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_downloadable_internal', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recordings_case_id'), 'recordings', ['case_id'], unique=False)
    op.create_index(op.f('ix_recordings_meeting_id'), 'recordings', ['meeting_id'], unique=False)
    op.create_table('document_access_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('viewer_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['viewer_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_access_logs_document_id'), 'document_access_logs', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_access_logs_viewer_user_id'), 'document_access_logs', ['viewer_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_access_logs_viewer_user_id'), table_name='document_access_logs')
    op.drop_index(op.f('ix_document_access_logs_document_id'), table_name='document_access_logs')
    op.drop_table('document_access_logs')
    op.drop_index(op.f('ix_recordings_meeting_id'), table_name='recordings')
    op.drop_index(op.f('ix_recordings_case_id'), table_name='recordings')
    op.drop_table('recordings')
    op.drop_index(op.f('ix_notice_deliveries_notice_id'), table_name='notice_deliveries')
    op.drop_table('notice_deliveries')
    op.drop_index(op.f('ix_documents_case_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_victim_accounts_case_id'), table_name='victim_accounts')
    op.drop_table('victim_accounts')
    op.drop_index(op.f('ix_otp_sessions_expires_at'), table_name='otp_sessions')
    op.drop_index(op.f('ix_otp_sessions_case_id'), table_name='otp_sessions')
    op.drop_table('otp_sessions')
    op.drop_index(op.f('ix_notices_case_id'), table_name='notices')
    op.drop_table('notices')
    op.drop_index(op.f('ix_meetings_scheduled_at'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_case_id'), table_name='meetings')
    op.drop_table('meetings')
    op.drop_table('case_rules_state')
    op.drop_index(op.f('ix_case_parties_case_id'), table_name='case_parties')
    op.drop_table('case_parties')
    op.drop_index(op.f('ix_case_milestones_case_id'), table_name='case_milestones')
    op.drop_table('case_milestones')
    op.drop_index(op.f('ix_case_import_rows_import_id'), table_name='case_import_rows')
    op.drop_table('case_import_rows')
    op.drop_table('case_arbitration')
    op.drop_index(op.f('ix_cases_status'), table_name='cases')
    op.drop_index(op.f('ix_cases_ref_no'), table_name='cases')
    op.drop_index(op.f('ix_cases_assigned_advocate_id'), table_name='cases')
    op.drop_table('cases')
    op.drop_table('case_imports')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
