"""notice table updated

Revision ID: f3e9966b3161
Revises: 7855c7ffd234
Create Date: 2026-03-11 10:10:06.292997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3e9966b3161'
down_revision: Union[str, Sequence[str], None] = '7855c7ffd234'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notice_attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('notice_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['notice_id'], ['notices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notice_attachments_document_id'), 'notice_attachments', ['document_id'], unique=False)
    op.create_index(op.f('ix_notice_attachments_notice_id'), 'notice_attachments', ['notice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notice_attachments_notice_id'), table_name='notice_attachments')
    op.drop_index(op.f('ix_notice_attachments_document_id'), table_name='notice_attachments')
    op.drop_table('notice_attachments')
    # ### end Alembic commands ###
